### ISSUE TITLE
Axis labels don't match axis value

### ISSUE THREAD

**Issue by liz-is** [lazappi/clustree#44] opened 2020-02-26 15:45 UTC
Hi, 
This is a nice package!

I noticed that when using `show_axis = TRUE`, the axis labels don't match the resolutions used / the node colours. For reference, this is using a Seurat object.

![clustree_example](https://user-images.githubusercontent.com/3035709/75360500-2f5ae680-58b6-11ea-9b93-925f0ce67ce0.jpg)

Here for example, the top row has the axis label 0.2 but the node is labelled 0 (which seems to be correct!).

In this case I first ran clustering with resolutions 0.2-1.4, and added clustering with resolution = 0 later, so the "0" column comes after the other columns in the `seurat@meta.data` data frame. I wonder if the order of column names is used to set the axis labels? 

Edit: this does seem to depend on the order of the column names. I removed the columns and re-ran the clustering providing `resolution = c(0.2, 0, 1.1, 0.8)`, and both the columns and axis labels are also in that order.

**Comment by lazappi** [comment] 2020-02-27 07:47
Hi @liz-is 

That definitely looks like a bug. I think you are right that the labels must be coming from the column order instead of the sorted resolution order.

Can you please make a small reproducible example (maybe using the `iris_clusts` dataset that I could use to test this?

**Comment by liz-is** [comment] 2020-02-27 09:15
Sure!

```
library(clustree)
data("iris_clusts")

reorder <- c("Sepal.Length","Sepal.Width", "Petal.Length", "Petal.Width", "Species",
             "K3", "K4", "K1", "K5", "K2", "PC1", "PC2")

iris_clusts2 <- iris_clusts[, reorder]
clustree(iris_clusts2, prefix = "K", show_axis = TRUE)
```

![plot_zoom](https://user-images.githubusercontent.com/3035709/75429365-f4a28e00-5949-11ea-9c1e-34dad0149ef0.png)

**Comment by liz-is** [comment] 2020-02-27 09:20
I think the relevant code is here: https://github.com/lazappi/clustree/blob/master/R/clustree.R#L334

Looks like if you use `sort(res_clean, decreasing = TRUE)` in place of `rev(res_clean)`, it should be solved. :)

**Comment by lazappi** [comment] 2020-02-28 07:37
Great! Thanks for the example and that looks like it could be the problem. 👍 If you want to submit a pull request to the `develop` branch with this fix that would be great and I would be happy to add you as a contributor to the package. Otherwise I will do it next time I have a chance to do some **clustree** development.

**Comment by lazappi** [comment] 2020-03-19 11:21
This should be fixed in the development version now. You can install it with `remotes::install_github("lazappi/clustree@develop")`. Feel free to test it and see if it works for you. This issue will get closed when I merge to `master`.

**Closed** 2020-06-14 12:29 UTC
Labels: bug
